name 'mburger-opentsdb'
version '0.0.1'

author 'Markus Burger'
license 'Apache2'
source 'https://github.com/mburger/puppet-opentsdb'
summary 'Puppet module for opentsdb'
description 'This module installs and manages opentsdb. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
